spring.application.name=everest-backend

# PostgreSQL Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Logging
logging.level.root=INFO
logging.level.no.everestforsikring.backend=INFO
logging.level.org.hibernate.SQL=INFO

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Frontend origin
cors.allowed.origin=${CORS_ALLOWED_ORIGIN}


#Mock systems base url
mock.core-system.base-url=${MOCK_CORE_SYSTEM_BASE_URL}
mock.letter-service.base-url=${MOCK_LETTER_SERVICE_BASE_URL}